name: Fetch JSON Data

on:
<<<<<<< HEAD
  schedule:
    - cron: '*/5  * * * *' # 每天 UTC 时间 04:00 执行
=======
>>>>>>> jiang
  workflow_dispatch:

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
<<<<<<< HEAD
          ref:'jiang'
=======
          ref: 'jiang' 
>>>>>>> jiang

      - name: Fetch JSON data
        run: |
          curl https://api.dabing.one > src/resources/data.json
<<<<<<< HEAD

=======
>>>>>>> jiang
      - name: Save JSON data to repository
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
<<<<<<< HEAD
          git checkout -b jiang
=======
          git checkout jiang || git checkout -b jiang
>>>>>>> jiang
          git pull
          git add src/resources/data.json
          git commit -m "Update data.json"
          git push origin jiang
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
