name: Fetch JSON Data

on:
  schedule:
    - cron: '0 20 * * *' # 每天 UTC 时间 04:00 执行
  workflow_dispatch:

jobs:
  fetch-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Fetch JSON data
        run: |
          curl https://api.dabing.one > src/resources/data.json

      - name: Save JSON data to repository
        run: |
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git config --global user.name "GitHub Actions"
          git checkout -b jiang
          git config pull.rebase false
          git pull origin jiang
          git add src/resources/data.json
          git commit -m "Update data.json"
          git push origin jiang
        env:
          GITHUB_TOKEN: ${{ secrets.ACTION_TOKEN }}
